
name: Build LEDE openclash

on:
  workflow_dispatch:
  schedule:
        - cron: 0 18 * * *
        - cron: 0 6 * * *

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      LEDE_REPO: game760/lede
      LEDE_BRANCH: main
      CONFIG_FILE: clash.config
      FEEDS_FILE: clash_feeds.conf.default
      WORK_DIR: /mnt/lede
      FIRMWARE_PATH: /mnt/lede/bin/targets/**/*
      DELETE_PATH: /mnt/lede/bin/targets/

    steps:
      - name: 检查仓库
        uses: actions/checkout@v4

      - name: 创建工作目录
        run: |
          sudo mkdir -p ${{ env.WORK_DIR }}
          sudo chmod 777 ${{ env.WORK_DIR }}
          echo "==== 磁盘空间 ===="
          df -h
          
      - name: 设置时间
        run: |
          echo "TIMES=$(TZ=Asia/Shanghai date +%Y-%m-%d_%H:%M)" >> $GITHUB_ENV

      - name: 安装依赖
        run: |
          sudo apt update -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
            genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
            libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
            libreadline-dev libssl-dev libtool llvm libnsl-dev ninja-build p7zip p7zip-full patch pkgconf \
            python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
            swig texinfo uglifyjs upx-ucl unzip wget xmlto xxd zlib1g-dev tree
            
      - name: 拉取源码
        run: |
          git clone https://github.com/${{ env.LEDE_REPO }}.git \
            ${{ env.WORK_DIR }} \
            -b ${{ env.LEDE_BRANCH }} --depth 1 --single-branch

      - name : 修改版本
        run: |
           cp ./scripts/auto_version_date.sh ${{ env.WORK_DIR }}/auto_version_date.sh
           cd ${{ env.WORK_DIR }}
           chmod +x auto_version_date.sh
           ./auto_version_date.sh
           
      - name: 复制feeds配置
        run: |
          cp -f ./configs/${{ env.FEEDS_FILE }} ${{ env.WORK_DIR }}/feeds.conf.default

      - name: 更新安装软件源
        run: |
          cd ${{ env.WORK_DIR }}
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 复制编译配置
        run: |
          cp -f ./configs/${{ env.CONFIG_FILE }} ${{ env.WORK_DIR }}/.config

      - name: 下载依赖
        run: |
          cd ${{ env.WORK_DIR }}
          make defconfig
          make download -j1
          
      - name: 编译固件
        run: |
          cd ${{ env.WORK_DIR }}
          make -j2
          
      - name: 整理固件
        run: |
          cd ${{ env.WORK_DIR }}
          find ${{ env.DELETE_PATH }} -type f \
            ! -name "*.tar.gz" \
            ! -name "*.img" \
            ! -name "*.img.gz" \
            -delete

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: /mnt/lede/bin/targets/**/*
          if-no-files-found: warn
          retention-days: 3

      - name: 上传到Release
        uses: ncipollo/release-action@v1
        with:
          tag: openclash
          name: LEDE x86_64_openclash
          body: |
                ### ${{ env.TIMES }}
                - 默认IP：192.168.1.1
                - 默认密码：password
          artifacts: /mnt/lede/bin/targets/**/*
          allowUpdates: true
          replaceArtifacts: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.LEDE_ALL }}
